/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AAppelfunctionExpr6 extends PExpr6
{
    private PAppelf _appelf_;

    public AAppelfunctionExpr6()
    {
        // Constructor
    }

    public AAppelfunctionExpr6(
        @SuppressWarnings("hiding") PAppelf _appelf_)
    {
        // Constructor
        setAppelf(_appelf_);

    }

    @Override
    public Object clone()
    {
        return new AAppelfunctionExpr6(
            cloneNode(this._appelf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppelfunctionExpr6(this);
    }

    public PAppelf getAppelf()
    {
        return this._appelf_;
    }

    public void setAppelf(PAppelf node)
    {
        if(this._appelf_ != null)
        {
            this._appelf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._appelf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._appelf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._appelf_ == child)
        {
            this._appelf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._appelf_ == oldChild)
        {
            setAppelf((PAppelf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
