/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADeriveDeclarvar extends PDeclarvar
{
    private TEntier _entier_;
    private TIdentif _identif_;
    private TCl _cl_;
    private PExpr99 _expr99_;
    private TCr _cr_;

    public ADeriveDeclarvar()
    {
        // Constructor
    }

    public ADeriveDeclarvar(
        @SuppressWarnings("hiding") TEntier _entier_,
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TCl _cl_,
        @SuppressWarnings("hiding") PExpr99 _expr99_,
        @SuppressWarnings("hiding") TCr _cr_)
    {
        // Constructor
        setEntier(_entier_);

        setIdentif(_identif_);

        setCl(_cl_);

        setExpr99(_expr99_);

        setCr(_cr_);

    }

    @Override
    public Object clone()
    {
        return new ADeriveDeclarvar(
            cloneNode(this._entier_),
            cloneNode(this._identif_),
            cloneNode(this._cl_),
            cloneNode(this._expr99_),
            cloneNode(this._cr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeriveDeclarvar(this);
    }

    public TEntier getEntier()
    {
        return this._entier_;
    }

    public void setEntier(TEntier node)
    {
        if(this._entier_ != null)
        {
            this._entier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entier_ = node;
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TCl getCl()
    {
        return this._cl_;
    }

    public void setCl(TCl node)
    {
        if(this._cl_ != null)
        {
            this._cl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cl_ = node;
    }

    public PExpr99 getExpr99()
    {
        return this._expr99_;
    }

    public void setExpr99(PExpr99 node)
    {
        if(this._expr99_ != null)
        {
            this._expr99_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr99_ = node;
    }

    public TCr getCr()
    {
        return this._cr_;
    }

    public void setCr(TCr node)
    {
        if(this._cr_ != null)
        {
            this._cr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._entier_)
            + toString(this._identif_)
            + toString(this._cl_)
            + toString(this._expr99_)
            + toString(this._cr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._entier_ == child)
        {
            this._entier_ = null;
            return;
        }

        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._cl_ == child)
        {
            this._cl_ = null;
            return;
        }

        if(this._expr99_ == child)
        {
            this._expr99_ = null;
            return;
        }

        if(this._cr_ == child)
        {
            this._cr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._entier_ == oldChild)
        {
            setEntier((TEntier) newChild);
            return;
        }

        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._cl_ == oldChild)
        {
            setCl((TCl) newChild);
            return;
        }

        if(this._expr99_ == oldChild)
        {
            setExpr99((PExpr99) newChild);
            return;
        }

        if(this._cr_ == oldChild)
        {
            setCr((TCr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
