/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AEcrInstr extends PInstr
{
    private PWrite _write_;

    public AEcrInstr()
    {
        // Constructor
    }

    public AEcrInstr(
        @SuppressWarnings("hiding") PWrite _write_)
    {
        // Constructor
        setWrite(_write_);

    }

    @Override
    public Object clone()
    {
        return new AEcrInstr(
            cloneNode(this._write_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEcrInstr(this);
    }

    public PWrite getWrite()
    {
        return this._write_;
    }

    public void setWrite(PWrite node)
    {
        if(this._write_ != null)
        {
            this._write_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._write_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._write_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._write_ == child)
        {
            this._write_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._write_ == oldChild)
        {
            setWrite((PWrite) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
