/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AParamListexpr extends PListexpr
{
    private PExpr99 _expr99_;
    private PListexpr2 _listexpr2_;

    public AParamListexpr()
    {
        // Constructor
    }

    public AParamListexpr(
        @SuppressWarnings("hiding") PExpr99 _expr99_,
        @SuppressWarnings("hiding") PListexpr2 _listexpr2_)
    {
        // Constructor
        setExpr99(_expr99_);

        setListexpr2(_listexpr2_);

    }

    @Override
    public Object clone()
    {
        return new AParamListexpr(
            cloneNode(this._expr99_),
            cloneNode(this._listexpr2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamListexpr(this);
    }

    public PExpr99 getExpr99()
    {
        return this._expr99_;
    }

    public void setExpr99(PExpr99 node)
    {
        if(this._expr99_ != null)
        {
            this._expr99_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr99_ = node;
    }

    public PListexpr2 getListexpr2()
    {
        return this._listexpr2_;
    }

    public void setListexpr2(PListexpr2 node)
    {
        if(this._listexpr2_ != null)
        {
            this._listexpr2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listexpr2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr99_)
            + toString(this._listexpr2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr99_ == child)
        {
            this._expr99_ = null;
            return;
        }

        if(this._listexpr2_ == child)
        {
            this._listexpr2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr99_ == oldChild)
        {
            setExpr99((PExpr99) newChild);
            return;
        }

        if(this._listexpr2_ == oldChild)
        {
            setListexpr2((PListexpr2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
