/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AProgrammesuite extends PProgrammesuite
{
    private PListedefonction _listedefonction_;

    public AProgrammesuite()
    {
        // Constructor
    }

    public AProgrammesuite(
        @SuppressWarnings("hiding") PListedefonction _listedefonction_)
    {
        // Constructor
        setListedefonction(_listedefonction_);

    }

    @Override
    public Object clone()
    {
        return new AProgrammesuite(
            cloneNode(this._listedefonction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgrammesuite(this);
    }

    public PListedefonction getListedefonction()
    {
        return this._listedefonction_;
    }

    public void setListedefonction(PListedefonction node)
    {
        if(this._listedefonction_ != null)
        {
            this._listedefonction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listedefonction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listedefonction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listedefonction_ == child)
        {
            this._listedefonction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listedefonction_ == oldChild)
        {
            setListedefonction((PListedefonction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
