/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASiKeyword extends PKeyword
{
    private PIf _if_;

    public ASiKeyword()
    {
        // Constructor
    }

    public ASiKeyword(
        @SuppressWarnings("hiding") PIf _if_)
    {
        // Constructor
        setIf(_if_);

    }

    @Override
    public Object clone()
    {
        return new ASiKeyword(
            cloneNode(this._if_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASiKeyword(this);
    }

    public PIf getIf()
    {
        return this._if_;
    }

    public void setIf(PIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((PIf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
