/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleDeclarvar extends PDeclarvar
{
    private TEntier _entier_;
    private TIdentif _identif_;

    public ASimpleDeclarvar()
    {
        // Constructor
    }

    public ASimpleDeclarvar(
        @SuppressWarnings("hiding") TEntier _entier_,
        @SuppressWarnings("hiding") TIdentif _identif_)
    {
        // Constructor
        setEntier(_entier_);

        setIdentif(_identif_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleDeclarvar(
            cloneNode(this._entier_),
            cloneNode(this._identif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleDeclarvar(this);
    }

    public TEntier getEntier()
    {
        return this._entier_;
    }

    public void setEntier(TEntier node)
    {
        if(this._entier_ != null)
        {
            this._entier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entier_ = node;
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._entier_)
            + toString(this._identif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._entier_ == child)
        {
            this._entier_ = null;
            return;
        }

        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._entier_ == oldChild)
        {
            setEntier((TEntier) newChild);
            return;
        }

        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
