/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASuitefonctionDefonction2 extends PDefonction2
{
    private PDefonction3 _defonction3_;

    public ASuitefonctionDefonction2()
    {
        // Constructor
    }

    public ASuitefonctionDefonction2(
        @SuppressWarnings("hiding") PDefonction3 _defonction3_)
    {
        // Constructor
        setDefonction3(_defonction3_);

    }

    @Override
    public Object clone()
    {
        return new ASuitefonctionDefonction2(
            cloneNode(this._defonction3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuitefonctionDefonction2(this);
    }

    public PDefonction3 getDefonction3()
    {
        return this._defonction3_;
    }

    public void setDefonction3(PDefonction3 node)
    {
        if(this._defonction3_ != null)
        {
            this._defonction3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._defonction3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._defonction3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._defonction3_ == child)
        {
            this._defonction3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._defonction3_ == oldChild)
        {
            setDefonction3((PDefonction3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
