/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASuitefonction2Defonction2 extends PDefonction2
{
    private PListedeclarvar _listedeclarvar_;
    private TPointVirgule _pointVirgule_;
    private PDefonction3 _defonction3_;

    public ASuitefonction2Defonction2()
    {
        // Constructor
    }

    public ASuitefonction2Defonction2(
        @SuppressWarnings("hiding") PListedeclarvar _listedeclarvar_,
        @SuppressWarnings("hiding") TPointVirgule _pointVirgule_,
        @SuppressWarnings("hiding") PDefonction3 _defonction3_)
    {
        // Constructor
        setListedeclarvar(_listedeclarvar_);

        setPointVirgule(_pointVirgule_);

        setDefonction3(_defonction3_);

    }

    @Override
    public Object clone()
    {
        return new ASuitefonction2Defonction2(
            cloneNode(this._listedeclarvar_),
            cloneNode(this._pointVirgule_),
            cloneNode(this._defonction3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuitefonction2Defonction2(this);
    }

    public PListedeclarvar getListedeclarvar()
    {
        return this._listedeclarvar_;
    }

    public void setListedeclarvar(PListedeclarvar node)
    {
        if(this._listedeclarvar_ != null)
        {
            this._listedeclarvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listedeclarvar_ = node;
    }

    public TPointVirgule getPointVirgule()
    {
        return this._pointVirgule_;
    }

    public void setPointVirgule(TPointVirgule node)
    {
        if(this._pointVirgule_ != null)
        {
            this._pointVirgule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pointVirgule_ = node;
    }

    public PDefonction3 getDefonction3()
    {
        return this._defonction3_;
    }

    public void setDefonction3(PDefonction3 node)
    {
        if(this._defonction3_ != null)
        {
            this._defonction3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._defonction3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listedeclarvar_)
            + toString(this._pointVirgule_)
            + toString(this._defonction3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listedeclarvar_ == child)
        {
            this._listedeclarvar_ = null;
            return;
        }

        if(this._pointVirgule_ == child)
        {
            this._pointVirgule_ = null;
            return;
        }

        if(this._defonction3_ == child)
        {
            this._defonction3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listedeclarvar_ == oldChild)
        {
            setListedeclarvar((PListedeclarvar) newChild);
            return;
        }

        if(this._pointVirgule_ == oldChild)
        {
            setPointVirgule((TPointVirgule) newChild);
            return;
        }

        if(this._defonction3_ == oldChild)
        {
            setDefonction3((PDefonction3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
