/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASuitexprBloc2 extends PBloc2
{
    private PInstr _instr_;
    private PBloc2 _bloc2_;

    public ASuitexprBloc2()
    {
        // Constructor
    }

    public ASuitexprBloc2(
        @SuppressWarnings("hiding") PInstr _instr_,
        @SuppressWarnings("hiding") PBloc2 _bloc2_)
    {
        // Constructor
        setInstr(_instr_);

        setBloc2(_bloc2_);

    }

    @Override
    public Object clone()
    {
        return new ASuitexprBloc2(
            cloneNode(this._instr_),
            cloneNode(this._bloc2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuitexprBloc2(this);
    }

    public PInstr getInstr()
    {
        return this._instr_;
    }

    public void setInstr(PInstr node)
    {
        if(this._instr_ != null)
        {
            this._instr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instr_ = node;
    }

    public PBloc2 getBloc2()
    {
        return this._bloc2_;
    }

    public void setBloc2(PBloc2 node)
    {
        if(this._bloc2_ != null)
        {
            this._bloc2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bloc2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instr_)
            + toString(this._bloc2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instr_ == child)
        {
            this._instr_ = null;
            return;
        }

        if(this._bloc2_ == child)
        {
            this._bloc2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instr_ == oldChild)
        {
            setInstr((PInstr) newChild);
            return;
        }

        if(this._bloc2_ == oldChild)
        {
            setBloc2((PBloc2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
