/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASuitexprBloc2 extends PBloc2
{
    private PExpr99 _expr99_;
    private TPointVirgule _pointVirgule_;
    private PBloc2 _bloc2_;

    public ASuitexprBloc2()
    {
        // Constructor
    }

    public ASuitexprBloc2(
        @SuppressWarnings("hiding") PExpr99 _expr99_,
        @SuppressWarnings("hiding") TPointVirgule _pointVirgule_,
        @SuppressWarnings("hiding") PBloc2 _bloc2_)
    {
        // Constructor
        setExpr99(_expr99_);

        setPointVirgule(_pointVirgule_);

        setBloc2(_bloc2_);

    }

    @Override
    public Object clone()
    {
        return new ASuitexprBloc2(
            cloneNode(this._expr99_),
            cloneNode(this._pointVirgule_),
            cloneNode(this._bloc2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuitexprBloc2(this);
    }

    public PExpr99 getExpr99()
    {
        return this._expr99_;
    }

    public void setExpr99(PExpr99 node)
    {
        if(this._expr99_ != null)
        {
            this._expr99_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr99_ = node;
    }

    public TPointVirgule getPointVirgule()
    {
        return this._pointVirgule_;
    }

    public void setPointVirgule(TPointVirgule node)
    {
        if(this._pointVirgule_ != null)
        {
            this._pointVirgule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pointVirgule_ = node;
    }

    public PBloc2 getBloc2()
    {
        return this._bloc2_;
    }

    public void setBloc2(PBloc2 node)
    {
        if(this._bloc2_ != null)
        {
            this._bloc2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bloc2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr99_)
            + toString(this._pointVirgule_)
            + toString(this._bloc2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr99_ == child)
        {
            this._expr99_ = null;
            return;
        }

        if(this._pointVirgule_ == child)
        {
            this._pointVirgule_ = null;
            return;
        }

        if(this._bloc2_ == child)
        {
            this._bloc2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr99_ == oldChild)
        {
            setExpr99((PExpr99) newChild);
            return;
        }

        if(this._pointVirgule_ == oldChild)
        {
            setPointVirgule((TPointVirgule) newChild);
            return;
        }

        if(this._bloc2_ == oldChild)
        {
            setBloc2((PBloc2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
