/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AVreuiInstr extends PInstr
{
    private PInstructfonction _instructfonction_;

    public AVreuiInstr()
    {
        // Constructor
    }

    public AVreuiInstr(
        @SuppressWarnings("hiding") PInstructfonction _instructfonction_)
    {
        // Constructor
        setInstructfonction(_instructfonction_);

    }

    @Override
    public Object clone()
    {
        return new AVreuiInstr(
            cloneNode(this._instructfonction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVreuiInstr(this);
    }

    public PInstructfonction getInstructfonction()
    {
        return this._instructfonction_;
    }

    public void setInstructfonction(PInstructfonction node)
    {
        if(this._instructfonction_ != null)
        {
            this._instructfonction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructfonction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructfonction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructfonction_ == child)
        {
            this._instructfonction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructfonction_ == oldChild)
        {
            setInstructfonction((PInstructfonction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
