/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TTantque extends Token
{
    public TTantque()
    {
        super.setText("tantque");
    }

    public TTantque(int line, int pos)
    {
        super.setText("tantque");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTantque(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTantque(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTantque text.");
    }
}
